# Generated by Django 2.1.3 on 2018-11-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc_management', '0004_auto_20181120_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='ucsf_rating',
            new_name='uscf_rating',
        ),
    ]
