# Generated by Django 2.1.3 on 2018-11-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_management', '0005_auto_20181120_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
    ]
