# Generated by Django 2.1.3 on 2018-11-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_management', '0007_auto_20181120_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_on', models.DateField(auto_now_add=True, verbose_name='Played On')),
                ('updated_at', models.DateField(auto_now=True)),
                ('batch_id', models.IntegerField(blank=True, null=True, verbose_name='Batch Number')),
                ('result', models.IntegerField(choices=[(0, 'Black Won!'), (1, 'Draw!'), (2, 'White Won!')], verbose_name='Result')),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to='cc_management.Player', verbose_name='Black Player')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cc_management.Club', verbose_name='Club Name')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='cc_management.Player', verbose_name='White Player')),
            ],
        ),
    ]
