# Generated by Django 2.1.3 on 2018-11-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_management', '0008_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Processed?'),
        ),
    ]
