# Generated by Django 2.1.3 on 2018-11-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_management', '0002_club_classifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('uscf_id', models.IntegerField(blank=True)),
                ('ucsf_rating', models.IntegerField(blank=True)),
                ('rating', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('grade', models.IntegerField(blank=True, choices=[(0, 'Kintergarten'), (1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th')])),
                ('classification', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cc_management.Club_Classifications')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cc_management.Club')),
            ],
        ),
    ]
