# Generated by Django 2.1.3 on 2018-11-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_management', '0003_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(0, 'Kintergarten'), (1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='ucsf_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='uscf_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
