# Generated by Django 2.1.3 on 2018-11-22 22:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc_management', '0009_game_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
