# Generated by Django 2.1.3 on 2018-11-23 15:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_management', '0010_game_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_on', models.DateField(auto_now_add=True, verbose_name='Processed On')),
                ('updated_at', models.DateField(auto_now=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cc_management.Club', verbose_name='Club Name')),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=1200, verbose_name='Club Rating'),
        ),
    ]
